#!/bin/bash

set -e

# install fonts
[ -d ~/.local/share/fonts ] || ( git clone https://github.com/powerline/fonts.git --depth=1 /tmp/fonts && /tmp/fonts/install.sh )

[ -d ~/.fzf/shell ] || mkdir -p ~/.fzf/shell

[ -f ~/.zshenv ] || ln -s $PWD/zshenv ~/.zshenv
[ -f ~/.zshrc ] || ln -s $PWD/zshrc ~/.zshrc
[ -d ~/.zsh ] || ln -s $PWD/zsh ~/.zsh

[ -f ~/.vimrc ] || ln -s $PWD/vimrc ~/.vimrc
[ -d ~/.vim ] || ln -s $PWD/vim ~/.vim

[ -f ~/.tmux.conf ] || ln -s $PWD/tmux.conf ~/.tmux.conf
[ -d ~/.tmux ] || ln -s $PWD/tmux ~/.tmux

[ -f ~/.gitconfig ] || ln -s $PWD/gitconfig ~/.gitconfig
[ -f ~/.gitignore ] || ln -s $PWD/gitignore ~/.gitignore

[ -f ~/.bashrc ] || ln -s $PWD/bashrc ~/.bashrc

[ -f ~/.curlrc ] || ln -s $PWD/curlrc ~/.curlrc

[ -f ~/.taskrc ] || ln -s $PWD/taskrc ~/.taskrc

[ -f ~/.inputrc ] || ln -s $PWD/inputrc ~/.inputrc

[ -f ~/.kube/kuberc ] || ln -s $PWD/kuberc ~/.kube/kuberc

[ -f ~/.dir_colors ] || ln -s $PWD/dir_colors ~/.dir_colors

[ -f ~/.psqlrc ] || ln -s $PWD/psqlrc ~/.psqlrc

[ -f ~/.my.cnf ] || ln -s $PWD/mysql.cnf ~/.my.cnf
[ -d ~/.mysqlsh ] || (mkdir -p ~/.mysqlsh && ln -s $PWD/mysql_prompt.json ~/.mysqlsh/prompt.json)

OSTYPE=`uname`

if [[ "$OSTYPE" == "Linux" ]]; then
  [ -f ~/.alacritty.toml ] || ln -s $PWD/alacritty.toml ~/.alacritty.toml
else
  mkdir -p  ~/.config/alacritty
  [ -f ~/.config/alacritty/alacritty.toml ] || ln -s $PWD/alacritty.macos.toml ~/.config/alacritty/alacritty.toml
fi

echo "Done."
