#!/bin/bash

function fail {
  printf "$1\n\033[91merror:\033[0m word '$2' was not found\r\n"
  exit 1
}

dict=${DICTIONARY:-/usr/share/dict/words}
commit_message=`head -n1 $1`

for word in `sed -E 's/([0-9]+)|(:|\.)+//g' <<< $commit_message` ; do
  rg $word $dict > /dev/null || fail "$commit_message" "$word"
done

